/**
 * Author:    Jantzen Allphin
 * Partner:   None
 * Date:      September 23, 2020
 * Course:    CS 4540, University of Utah, School of Computing
 * Copyright: CS 4540 and Jantzen Allphin - This work may not be copied for use in Academic Coursework.
 *
 * I, Jantzen Allphin, certify that I wrote this code (below) from scratch and did 
 * not copy it in part or whole from another source.  Any references used 
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 *
 *    Contains C# code for the ErrorViewModel of the web site. This code was generated by ASP.NET upon project creation.
 */

using System;

namespace URC.Models
{
    /// <summary>
    /// This class represents the ErrorViewModel.
    /// </summary> 
    public class ErrorViewModel
    {
        /// <summary>
        /// Represents the RequestId for this ErrorViewModel.
        /// </summary> 
        public string RequestId { get; set; }

        /// <summary>
        /// Returns true if RequestId is not Null or empty.
        /// </summary> 
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
